from . import area
from . import city_distance
from . import designation
from . import division
from . import doctor_stockist_retailer_res_partner
from . import doctor_support
from . import doctor_support_line
from . import employee
from . import employee_daily_call_report
from . import employee_sampling_and_gift_reporting
from . import employee_sampling_and_gift_reporting_line
from . import fiscal_period
from . import fiscal_year
from . import headquarters
from . import personal_order_booking
from . import personal_order_booking_line
from . import product
from . import sale_order
from . import stock_location
from . import stock_move
from . import stock_picking
from . import stock_warehouse
from . import tour_plan
from . import res_users
from . import employee_daily_call_report_line
from . import tour_plan_lines
from . import res_company
from . import setu_pharma_work_type
from . import approval_request
from . import res_config_settings
from . import setu_pharma_ex_headquater
from . import stockist_monthly_statement
from . import stockist_monthly_statement_line
from . import approval_request
from .import product_drug_contain
from . import res_partner_doctor_class
from . import res_city
